/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Template, Theme } from "@webpress/core";
export namespace Components {
    interface BstHeader {
    }
    interface BstHome {
        "query": Template.Query;
        "theme": Theme;
    }
    interface BstPrintPress {
    }
}
declare global {
    interface HTMLBstHeaderElement extends Components.BstHeader, HTMLStencilElement {
    }
    var HTMLBstHeaderElement: {
        prototype: HTMLBstHeaderElement;
        new (): HTMLBstHeaderElement;
    };
    interface HTMLBstHomeElement extends Components.BstHome, HTMLStencilElement {
    }
    var HTMLBstHomeElement: {
        prototype: HTMLBstHomeElement;
        new (): HTMLBstHomeElement;
    };
    interface HTMLBstPrintPressElement extends Components.BstPrintPress, HTMLStencilElement {
    }
    var HTMLBstPrintPressElement: {
        prototype: HTMLBstPrintPressElement;
        new (): HTMLBstPrintPressElement;
    };
    interface HTMLElementTagNameMap {
        "bst-header": HTMLBstHeaderElement;
        "bst-home": HTMLBstHomeElement;
        "bst-print-press": HTMLBstPrintPressElement;
    }
}
declare namespace LocalJSX {
    interface BstHeader {
    }
    interface BstHome {
        "query"?: Template.Query;
        "theme"?: Theme;
    }
    interface BstPrintPress {
    }
    interface IntrinsicElements {
        "bst-header": BstHeader;
        "bst-home": BstHome;
        "bst-print-press": BstPrintPress;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bst-header": LocalJSX.BstHeader & JSXBase.HTMLAttributes<HTMLBstHeaderElement>;
            "bst-home": LocalJSX.BstHome & JSXBase.HTMLAttributes<HTMLBstHomeElement>;
            "bst-print-press": LocalJSX.BstPrintPress & JSXBase.HTMLAttributes<HTMLBstPrintPressElement>;
        }
    }
}
